### ISSUE TITLE
Wrong tooltip position

### ISSUE THREAD

**Issue by mjakubczak** [Roche/ggtips#31]
Reproduction:
1. add some element to the demo app UI:
```
mainPanel = mainPanel(
  shiny::div(style = "height:400px;"), # like this one
  uiOutput(outputId = "myPlot")
)
```
2. Run demo app and scroll to bottom
3. Hover on some point
  - expected: a tooltip shows next to the point
  - observed: a tooltip appears above the plot (see screenshot)
![Screenshot from 2020-05-06 11-14-38](https://user-images.githubusercontent.com/29655451/81161392-cc5b8f00-8f8b-11ea-9208-991a39e7d005.png)

**Comment by cosi1** [comment]
@jcubic Could you please take a look?

**Comment by jcubic** [comment]
Yes I working on it.

**Comment by jcubic** [comment]
The problem was scrollbar and offset.

@cosi1 can you check the build it's failing after your last commit to master, maybe some deps change, it's first build after 2 months. You should always create PR, so this will not happen to have broken build in master. And if you can please update CHANGELONG if you changing version after each fix you add next version until you change DESCRIPTION so we will be able to easy track the changes and versions. We don't publish the package but users install from GitHub,

**Comment by cosi1** [comment]
@jcubic You're right. It was an emergency fix, but I should have filed a PR :-)

Updated CHANGELOG.md

**Comment by cosi1** [comment]
@jcubic Re: failing tests – seems like a function has been removed from `grid` in R 4.0.0

#33

**Comment by mjakubczak** [comment]
works fine, thank you guys!
