### ISSUE TITLE
Can the plots be exported to SVG files?

### ISSUE THREAD

**Issue by zmeers** [Roche/ggtips#69]
See question in title -- although now that I think about it, the tooltips might be relying on some JavaScript in the Shiny app...
Regardless, I'd love to be able to export some of the interactivity to an SVG file. Can you please let me know if this is possible?

Thanks,
Zoe

**Comment by jcubic** [comment]
With the current code, this is not possible, but I think we can check what we can do. The problem is that the tooltips are outside of SVG. It's a div that floats above the plot. For this to be possible we will need to put tooltips inside SVG, but the problem is that SVG is scalable and right now tooltips are not. It would look odd when you open SVG in a browser and tooltips are really small or really big. We will need to investigate if we can somehow make the tooltips the same size while the SVG is scaled. It may be problematic.

**Comment by zmeers** [comment]
Thanks -- let me know if you happen to find a solution, but yes I expected that the scale problem might affect SVG exports.
